version: "3.7"
services:
  main:
    container_name: main
    image: xu3cl40122/gc-service:latest
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - postgres_network
    depends_on: 
      - postgres
    ports:
      - 3000:3000
    restart: unless-stopped
    command: node dist/main

  postgres:
    container_name: postgres_container
    image: mdillon/postgis
    env_file:
      - db.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   env_file:
  #     - db.env
  #   volumes:
  #     - pgadmin:/root/.pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - postgres_network
  #   restart: unless-stopped

networks:
  postgres_network:

volumes:
  postgres:
  # pgadmin:
