version: "3.5"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - main
    networks:
      - gc_network
    ports:
      - 80:80
  main:
    container_name: main
    build:
      context: .
      # target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - gc_network
        # aliases:
        #   - backend
    depends_on: 
      - postgres
    ports:
      - 3000:3000
    restart: unless-stopped
    command: npm run start:dev

  postgres:
    container_name: postgres_container
    image: kartoza/postgis
    env_file:
      - db.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - gc_network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - db.env
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - gc_network
      - file_postgres
    restart: unless-stopped

networks:
  gc_network:
    # driver: bridge
  file_postgres:
    external:
      name: file_postgres
      
volumes:
  postgres:
  pgadmin:
