version: "3.7"
services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - postgres_network
      - redis_network
    depends_on: 
      - postgres
      - redis
    ports:
      - 3000:3000
    restart: unless-stopped
   

  postgres:
    container_name: postgres_container
    image: mdillon/postgis
    env_file:
      - db.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped

  redis:
    restart: unless-stopped
    container_name: redis
    image: redis:alpine
    networks:
      - redis_network
    ports:
      - 6379:6379
    volumes:
      - /data/redis-data:/data

networks:
  postgres_network:
  redis_network:
      
volumes:
  postgres:
  pgadmin:
