version: '3.5'
services:
  backend:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      my-network-name:
        aliases:
          - backend
    depends_on: 
      - postgres
    ports:
      - 3000:3000
    restart: unless-stopped
    command: npm run start:dev

  nginx-proxy:
    depends_on:
      - backend
    image: nginx:alpine
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      my-network-name:
        aliases:
          - proxy-name
    ports:
        - 1234:80

  postgres:
    image: kartoza/postgis
    env_file:
      - db.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      my-network-name:
        aliases:
          - postgres
    restart: unless-stopped
networks:
  my-network-name:

volumes:
  postgres: