version: "3.7"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    # image: nginx
    restart: unless-stopped
    # volumes:
    #   - ./nginx/local/nginx.conf:/etc/nginx/nginx.conf
    #   - ./nginx/local/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - main
    networks:
      - backend
    ports:
      - 80:80
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend
      - postgres_network
    depends_on: 
      - postgres
    ports:
      - 3000:3000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          # memory: 800M
    # command: npm run start:dev

  postgres:
    container_name: postgres_container
    # image: kartoza/postgis
    image: mdillon/postgis
    env_file:
      - db.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - db.env
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres_network
      # - file_postgres
    restart: unless-stopped

networks:
  postgres_network:
  backend:
    # driver: bridge
  # file_postgres:
  #   external:
  #     name: file_postgres
      
volumes:
  postgres:
  pgadmin:
